version: '3.9'

services:
  db:
    image: postgres
    restart: always
    container_name: ART
    environment:
      POSTGRES_USER: jay
      POSTGRES_PASSWORD: postgres
    ports:
      - "5555:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: